services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/srv/node/app # Corrected the placement of "volumes"
    networks:
      - app_net
    ports:
      - "9229:9229"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - app_net
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/usr/share/nginx/static:ro
      - ./html:/usr/share/nginx/html:ro
    depends_on:
      - app

networks:
  app_net:
    driver: bridge
