services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/srv/node/app
    networks:
      - app_net
    ports:
      - "3000:3000"
      - "9229:9229"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - app_net
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/usr/share/nginx/static:ro
      - ./html:/usr/share/nginx/html:ro
    depends_on:
      - app

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: node
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_net

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodata:/data/db
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  pgdata:
  mongodata: